### ISSUE TITLE
Future: Add support for darwin/arm64 binaries will available

### ISSUE THREAD

**Issue by robertpeteuil** [robertpeteuil/terraform-installer#8]
When darwin/arm64 binaries are available, adjust cpu detection logic to determine and create correct download URL for this platform/cpu.  (possibly combined logic adjustment with issue #7)

These binaries likely wont be available until [Go 1.16](https://tip.golang.org/doc/go1.16#darwin)

**Comment by robertpeteuil** [comment]
Moved to project kaban board

**Comment by tmatilai** [comment]
Hi Robert,
While I don't unfortunately have such a machine in my use, I would still be happy to have the support ready while waiting for the first official darwin/arm64 release. The same lack of machine means that I can't really test the detection logic either. Any change you know a reliable way? 😃

**Comment by robertpeteuil** [comment]
Unfortunately, I don't have an M1 machine to test on either.  

I think detecting the OS/CPU will likely be the easy bit, as I'll also need to combine a version check with the Arch detection (as only newer versions will be available for Arm).

Fortunately if you want to download the latest version, HashiCorp now has their own [Homebrew Tap](https://github.com/hashicorp/homebrew-tap)

**Comment by tmatilai** [comment]
I have verified that `uname -m` prints `arm64` on M1 machines (`x86_64` on Intel), so that could be a good option.

> Fortunately if you want to download the latest version, HashiCorp now has their own [Homebrew Tap](https://github.com/hashicorp/homebrew-tap)

Yeah, and Homebrew has their own Formulas and Bottles, even for arm64 already. 

But I'll need this for the [chtf](https://github.com/Yleisradio/chtf) version switcher for those who for whatever reason don't want to use Homebrew (in which case *all* Terraform releases can be found in [homebrew-terraforms](https://github.com/Yleisradio/homebrew-terraforms) Tap).
